

version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/config/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      restart: always
      container_name: eshop_php
      volumes:
          - "./:/var/www/html"
      ports:
        - "9000:9000"
  mysql:
      image: mysql:8.0
      container_name: eshop_db
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - ./docker/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}

  redis:
      image: redis:latest
      container_name: redis
      restart: always
      ports:
          - "6379:6379"
         
  